I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/mo3tazz1.rpy", line 13, in script
    $ carddeck = Deck()
  File "game/chapters/mo3tazz1.rpy", line 13, in <module>
    $ carddeck = Deck()
  File "game/script.rpy", line 140, in __init__
    self.build()
  File "game/script.rpy", line 152, in build
    self.cards.append(Card(suit, val, valuem, suitm))
NameError: global name 'valuem' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/mo3tazz1.rpy", line 13, in script
    $ carddeck = Deck()
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/chapters/mo3tazz1.rpy", line 13, in <module>
    $ carddeck = Deck()
  File "game/script.rpy", line 140, in __init__
    self.build()
  File "game/script.rpy", line 152, in build
    self.cards.append(Card(suit, val, valuem, suitm))
NameError: global name 'valuem' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Ha3oud 1.1
Tue Dec 28 09:15:50 2021
